version: '3.5'

services:

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    entrypoint: redis-server --appendonly yes
    restart: always
    networks:
      - internalNet

  jupyter_lab:
    container_name: jupyter_lab
    image: jupyter/datascience-notebook
    ports: 
      - "8888:8888"
    environment: 
      - JUPYTER_ENABLE_LAB=yes
    volumes: 
      - ./src/redis-with-python:/home/jovyan/work 
    #networks:
      - internalNet

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: dbroot@123
      MYSQL_DATABASE: db
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'dbuser@123'
    ports: 
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - internalNet

networks:
  internalNet:
    name: internal_net
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/16
        gateway: 172.20.0.1